<?php

class Page {

  private $title = '';
  private $tags = array();
  //tags which should be processed after the page has been parsed.
  //There maybe a chance that there are template tags within the database content.
  //We must parse the page, then parse it again for post parse tags.
  private $postParseTags = array();
  private $bits = array();
  private $content = "";
  //additional parsing data
  private $apd = array();

  function __construct( Registry $registry )
  {
    $this->registry = $registry;
  }

  public function getTitle()
  {
    $this->title;
  }

  public function setTitle()
  {
    $this->title = $title;
  }

  public function setContent( $content )
  {
    $this->content = $content;
  }

  public function addTag($key, $data)
  {
    $this->tags[$key] = $data;
  }

  public function removeTag($key)
  {
    unset($this->tags[$key]);
  }

  public function getTags()
  {
    return $this->tags;
  }

  public function addPPTag($key, $data)
  {
    $this->postParseTags[$key] = $data;
  }

  public function getPPTags()
  {
    return $thid->postParseTags;
  }

  public function addTemplateBit($tag, $bit)
  {
    $this->bits[$tag] = $bit;
  }

  public function addAdditionalParsingData($block, $tag, $condition, $extratag, $data)
  {
    $this->apd[$block] = array($tag => 
                           array('condition' => $condition, 
                                 'tag' => $extratag,
                                 'data' => $data)
                         );
  }

  public function getBits()
  {
    return $this->bits;
  }

  public function getAdditionalParsingData() 
  {
    return $this->apd;
  }

  /**
   * Gets a check of page content
   * @param String the tag wrapping the block ( <!-- START tag --> block <!-- END tag --> )
   * TODO: come back and understand the logic
   */
  public function getBlock($tag)
  {
    $tor = '';
    preg_match('#<!-- START ' . $tag . ' -->(.+?)<!-- END ' . $tag . ' -->#si',
      $this->content,
      $tor
    );

    $tor = str_replace('<!-- START ' . $tag . ' -->', "", $tor[0]);
    $tor = str_replace('<!-- END ' . $tag . ' -->', "", $tor);

    return $tor;
  }

  public function getContent()
  {
    return $this->content;
  }


  //TODO: come back and understand the logic
  public function getContentToPrint()
  {
    $this->content = preg_replace('#{form_(.+?)}#si', '', $this->content);
    $this->content = preg_replace('#{nbd_(.+?)}#si', '', $this->content);
    $this->content = str_replace('</body>', 
                       '<!-- Generated by our Fantastic Social Network --> </body>',
                       $this->content);
    return $this->content;
  }
}
?>
